[package]
name = "cool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cool"
path = "src/main.rs"


[dependencies]
lex = { path = "./lex" }
lexer = { path = "./lexer" }
parser = { path = "./parser" }

[features]
debug = []
